#+startup: overview indent
#+TITLE: Emacs configuration
#+AUTHOR: Raffael Golomingi

This is my emacs config file

* diminish

I don't want that every minor mode is cluttering my modeline.

#+begin_src emacs-lisp
(use-package diminish
  :ensure t)
#+end_src

* auto-package-update

I want to auto update packages. The default is every 7 days.

#+begin_src emacs-lisp
(use-package auto-package-update
  :ensure t
  :config
  (setq auto-package-update-delete-old-versions t)
  (setq auto-package-update-hide-results t)
  (auto-package-update-maybe))

#+end_src

* Default settings

** UTF-8 Please

#+begin_src emacs-lisp
(set-charset-priority 'unicode)
(setq locale-coding-system   'utf-8)   ; pretty
(set-terminal-coding-system  'utf-8)   ; pretty
(set-keyboard-coding-system  'utf-8)   ; pretty
(set-selection-coding-system 'utf-8)   ; please
(prefer-coding-system        'utf-8)   ; with sugar on top
(setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING))
;;(setq default-process-coding-system '(utf-8-unix . utf-8-unix))
#+end_src

** Garbage collection allow more than 20MB

This should trigger gc not so often.
#+begin_src emacs-lisp
(setq gc-cons-threshold 20000000)
#+end_src

** No backup files

#+begin_src emacs-lisp
(setq make-backup-files nil)
#+end_src

** Auto-Save in /tmp

#+begin_src emacs-lisp
(setq backup-directory-alist
      `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
      `((".*" ,temporary-file-directory t)))
#+end_src

** Always follow symlinks

#+begin_src emacs-lisp
(setq vc-follow-symlinks t)
#+end_src

** Sentences have one space after a period

#+begin_src emacs-lisp
(setq sentence-end-double-space nil)
#+end_src

** Confirm before closing Emacs

#+begin_src emacs-lisp
(setq confirm-kill-emacs 'y-or-n-p)
#+end_src

** Ask y/n instead of yes/no

#+begin_src emacs-lisp
(fset 'yes-or-no-p 'y-or-n-p)
#+end_src

** Auto revert files on change

#+begin_src emacs-lisp
(global-auto-revert-mode t)
#+end_src


** Shortcut for changing font size

Press Ctrl+1 for increasing the font and Ctrl+0 to decrease it.

#+begin_src emacs-lisp
(define-key global-map (kbd "C-1") 'text-scale-increase)
(define-key global-map (kbd "C-0") 'text-scale-decrease)
#+end_src

** Disable startup message

#+begin_src emacs-lisp
(setq inhibit-splash-screen t)
(setq inhibit-startup-message t)
#+end_src

** No GUI toolbar

#+begin_src emacs-lisp
(tool-bar-mode 0)
#+end_src

** Automatic line Breaks

Per default I want line breaks when reaching column 80.

#+begin_src emacs-lisp
(setq-default fill-column 80)
(add-hook 'text-mode-hook 'auto-fill-mode)
(diminish 'auto-fill-function)
#+end_src

** Ruler
I like to have a ruler at the top of my windows.
#+begin_src emacs-lisp
(add-hook 'window-configuration-change-hook (lambda () (ruler-mode 1)))
#+end_src

** Enable Narrow to region

#+begin_src emacs-lisp
(put 'narrow-to-region 'disabled nil)
#+end_src

** We dont need scroll bars

#+begin_src emacs-lisp
(scroll-bar-mode -1)
#+end_src

** Remeber cursor position when reopening files

#+begin_src emacs-lisp
(setq save-place-file "~/.emacs.d/saveplace")
(setq-default save-place t)
#+end_src

** no bell

#+begin_src emacs-lisp
(setq visible-bell t)
#+end_src

** auto completion

#+begin_src emacs-lisp
(use-package company
  :ensure t
  :defer t
  :diminish company-mode
  :init
  (global-company-mode))
#+end_src

** default font

#+begin_src emacs-lisp

;;  (add-to-list 'default-frame-alist '(font . "Hack-11"))

;;  (when (member "Hack" (font-family-list))
;;    (set-face-attribute 'default nil :font "Hack" :height 110))

(add-to-list 'default-frame-alist '(font . "IBM Plex Mono-11"))

(when (member "IBM Plex Mono" (font-family-list))
  (set-face-attribute 'default nil :font "IBM Plex Mono" :height 110))
#+end_src

** undo tree mode
#+begin_src emacs-lisp
(use-package undo-tree
  :ensure t
  :init (global-undo-tree-mode))
#+end_src

#+RESULTS:

** winner mode

Allows to ‘undo’ (and ‘redo’) changes in the window configuration with
the key commands ‘C-c left’ and ‘C-c right’.

#+begin_src emacs-lisp
(when (fboundp 'winner-mode)
  (winner-mode 1))
#+end_src

** Start in full screen

I want that emacs opens in fullscreen
#+begin_src emacs-lisp
(add-to-list 'default-frame-alist '(fullscreen . maximized))
  ;;(custom-set-variables
   ;;'(initial-frame-alist (quote ((fullscreen . maximized)))))
#+End_SRC


** Client settings

Change how you kill buffers if you open emacs as client
#+begin_src emacs-lisp
(add-hook 'server-switch-hook
          (lambda ()
            (when (current-local-map)
              (use-local-map (copy-keymap (current-local-map))))
            (when server-buffer-clients
              (local-set-key (kbd "C-x k") 'server-edit))))
#+end_src

** Emacs daemon settings
This function helps to shut down the emacs server and save any
modified buffers

#+begin_src emacs-lisp
(defun server-shutdown ()
  "Save buffers, Quit, and Shutdown (kill) server"
  (interactive)
  (save-some-buffers)
  (kill-emacs))
#+end_src

* Emojify
#+begin_src emacs-lisp
(use-package emojify
  :ensure t
  ;;:hook (after-init . global-emojify-mode)
  :config
  (setq emojify-program-contexts nil))

#+end_src

* Evil

#+begin_src emacs-lisp
(use-package evil
  :ensure t
  :init
  (setq evil-want-integration t)
  (setq evil-want-keybinding nil)
  (setq evil-undo-system 'undo-tree)
  :config
  (global-set-key (kbd "M-x")'execute-extended-command)
  (evil-mode 1))

(use-package evil-collection
  :after evil
  :ensure t
  :custom
  (evil-collection-calendar-want-org-bindings t)
  :init
  (evil-collection-init))


(use-package evil-leader
  :after evil
  :ensure t
  :init (global-evil-leader-mode)
  :config
  (progn
    (evil-leader/set-leader ",")
    (evil-leader/set-key
      "w" 'basic-save-buffer
      "s" 'flyspell-buffer
      "b" 'evil-buffer
      "q" 'evil-quit)))

;; don't show name in modeline
(diminish 'undo-tree-mode)
(diminish 'evil-collection-unimpaired-mode)

(use-package pdf-tools
  :ensure t
  :config
  (add-hook 'pdf-view-mode-hook
            (lambda ()
              (set (make-local-variable 'evil-emacs-state-cursor) (list nil))))
  (add-hook 'TeX-after-compilation-finished-functions #'TeX-revert-document-buffer)
  (add-hook 'pdf-view-mode-hook (lambda () (linum-mode -1)))
  (pdf-tools-install))



(use-package evil-smartparens
  :ensure t
  :diminish evil-smartparens-mode
  :config
  (add-hook 'smartparens-enabled-hook #'evil-smartparens-mode))
#+end_src

* Projectile

#+begin_src emacs-lisp
(use-package projectile
  :ensure t
  :defer t
  :diminish projectile-mode
  :config
  (projectile-global-mode))
#+end_src

* Helm

#+begin_src emacs-lisp
(use-package helm
  :ensure t
  :diminish helm-mode
  :init
  (require 'helm-config)
  :config
  (helm-mode 1)
  ;;(setq helm-autoresize-mode t)
  (setq helm-buffer-max-length 40)
  (global-set-key (kbd "M-x") #'helm-M-x)
  (global-set-key (kbd "C-x C-f") 'helm-find-files)
  (define-key helm-map (kbd "S-SPC") 'helm-toggle-visible-mark)
  (define-key helm-find-files-map (kbd "C-k") 'helm-find-files-up-one-level))
#+end_src


** Helm projectile

#+begin_src emacs-lisp
(use-package helm-projectile
  :bind (("C-S-P" . helm-projectile-switch-project)
         :map evil-normal-state-map
         ("C-p" . helm-projectile))
  :ensure t
  :config
  (evil-leader/set-key
    "ps" 'helm-projectile-ag
    "pa" 'helm-projectile-find-file-in-known-projects))
#+end_src

* Which-key

#+begin_src emacs-lisp
(use-package which-key
  :ensure t
  :diminish which-key-mode
  :config (which-key-mode) )
#+end_src

* Theming

** Theme to load
*** solarized

#+begin_src emacs-lisp
;;  (use-package solarized-theme
;;    :ensure t
;;    :defer t
   ; :init (load-theme 'solarized-dark t)
;;    )
#+end_src

*** zenburn

#+begin_src emacs-lisp
;;(use-package zenburn-theme
;;  :ensure t)

#+end_src

*** material

#+begin_src emacs-lisp

;  (use-package material-theme
;    :ensure t)

#+end_src


*** tangotango

#+begin_src emacs-lisp

;  (use-package tangotango-theme
;    :ensure t)

#+end_src

*** darcula

#+begin_src emacs-lisp

;;  (use-package darcula-theme
;;    :ensure t)

#+end_src

*** ample

#+begin_src emacs-lisp

;;(use-package ample-theme
;;  :defer t
;;  :ensure t)
#+end_src


*** sanityinc-tomorrow
#+begin_src emacs-lisp
;;(use-package  color-theme-sanityinc-tomorrow
;;  :ensure t
;;  :defer t)
#+end_src
*** gruvbox
#+begin_src emacs-lisp
;(use-package gruvbox-theme
;  :ensure t)
#+end_src

*** leuven
#+begin_src emacs-lisp
(use-package leuven-theme
  :ensure t)
#+end_src

*** load theme
#+begin_src emacs-lisp

;;(use-package color-theme :ensure t)
;;(load-theme 'gruvbox-light-hard t)
(load-theme 'leuven t)

;;(load-theme 'sanityinc-tomorrow-eighties t)
#+end_src
** Powerline

#+begin_src emacs-lisp
(use-package powerline
  :ensure t
  :config (powerline-default-theme ))
#+end_src

** Airline Themes

#+begin_src emacs-lisp
(use-package airline-themes
  :ensure t
  :init
  (setq powerline-utf-8-separator-left        #xe0b0
        powerline-utf-8-separator-right       #xe0b2
        airline-utf-glyph-separator-left      #xe0b0
        airline-utf-glyph-separator-right     #xe0b2
        airline-utf-glyph-subseparator-left   #xe0b1
        airline-utf-glyph-subseparator-right  #xe0b3
        airline-utf-glyph-branch              #xe0a0
        airline-utf-glyph-readonly            #xe0a2
        airline-utf-glyph-linenumber          #xe0a1)
  :config
  ;;(load-theme 'airline-solarized-gui t)
  ;;(load-theme 'airline-wombat t)
  ;;(load-theme 'airline-gruvbox-dark t)
  (load-theme 'airline-sol t))
#+end_src


** Custom function for dark and light themes

Since i like to switch between the solarized/tango light and dark theme i
made this little toggle function which loads the solarized/tango theme and
then also loads the airline theme again so the modeline is not messed
up :-)

#+begin_src emacs-lisp
(setq light-theme 'leuven)
(setq dark-theme 'leuven-dark)

(setq active-theme light-theme)

(defun toggle-light-theme ()
  (interactive)
  (if (eq active-theme dark-theme)
      (setq active-theme light-theme)
    (setq active-theme dark-theme))
  (load-theme active-theme t)
  (load-theme 'airline-sol t))

;;(toggle-light-theme)

(global-set-key (kbd "<f6>") 'toggle-light-theme)
#+end_src

* Dashboard

#+begin_src emacs-lisp
(use-package dashboard
  :ensure t
  :config
  (dashboard-setup-startup-hook)
  (setq dashboard-filter-agenda-entry 'dashboard-filter-agenda-by-todo)
  (add-to-list 'dashboard-items '(projects . 5) t)
  (if (daemonp)
      (setq initial-buffer-choice (lambda ()
                                    (get-buffer "*dashboard*")))))
#+end_src

* Plantuml

#+begin_src emacs-lisp
(use-package plantuml-mode
  :ensure t
  :config
  (setq plantuml-default-exec-mode 'jar)
  (setq org-plantuml-jar-path (expand-file-name "/usr/share/java/plantuml/plantuml.jar"))
  (add-to-list 'auto-mode-alist '("\\.plantuml\\'" . plantuml-mode)))

#+end_src

* mu4e

#+begin_src emacs-lisp
(require 'smtpmail)

;(setq auth-sources '("~/.authinfo.gpg"))

(use-package mu4e
  :commands mu4e
  :config
  ;;(setq mu4e-maildir "~/Maildir")
  ;;(setq mu4e-get-mail-command "offlineimap")
  (setq mu4e-maildir "~/Mail")
  (setq mu4e-get-mail-command "mbsync -a")
  (setq mu4e-update-interval 1200)
  (setq mu4e-attachement-dir "~/Downloads")
  (setq user-full-name "Raffael Golomingi")
  (setq mail-user-agent 'mu4e-user-agent)
  (setq mu4e-view-use-gnus t)
  (setq mu4e-view-show-adresses t)
  (setq mu4e-view-show-images t)
  (setq message-send-mail-function 'smtpmail-send-it)
  (setq message-kill-buffer-on-exit t)
  (setq mu4e-context-policy 'pick-first)
  ;;(setq mu4e-compose-signature t my-signature-file "~/.signature")
  (setq mu4e-compose-signature-auto-include nil)
  (setq mu4e-compose-dont-reply-to-self t)
  (setq mu4e-change-filenames-when-moving t)

  ;;because we have problem with some mails
  (setq shr-use-colors nil)
  ;;(setq shr-color-visible-luminance-min 60)
  ;;(setq shr-color-visible-distance-min 5)
  (add-to-list 'mu4e-view-actions '("ViewInBrowser" . mu4e-action-view-in-browser) t)
  ;(add-to-list 'mu4e-user-mail-address-list "raffael.affolter@protonmail.ch")
  ;(add-to-list 'mu4e-user-mail-address-list "raffael.affolter@protonmail.com")
  ;(add-to-list 'mu4e-user-mail-address-list "raffael.affolter@pm.me")
  ;(add-to-list 'mu4e-user-mail-address-list "affolraf@students.zhaw.ch")
  (setq mu4e-contexts
        `(,(make-mu4e-context
            :name "PROTONMAIL"
            :enter-func (lambda() (mu4e-message "Switch to Protonmail"))
            :match-func (lambda(msg)
                          (when msg
                            (s-prefix? "/Protonmail/" (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "raffael.golomingi@protonmail.ch")
                    (mu4e-sent-folder . "/Protonmail/Sent")
                    (mu4e-drafts-folder . "/Protonmail/Drafts")
                    (mu4e-trash-folder . "/Protonmail/Trash")
                    (smtpmail-default-smtp-server . "127.0.0.1")
                    (smtpmail-smtp-server . "127.0.0.1")
                    (smtpmail-local-domain . "127.0.0.1")
                    (smtpmail-smtp-user . "raffael.golomingi@protonmail.ch")
                    (smtpmail-stream-type . starttls)
                    (smtpmail-smtp-service . 1025)))

          ,(make-mu4e-context
            :name "ZHAW"
            :enter-func (lambda() (mu4e-message "Switch to ZHAW"))
            :match-func (lambda(msg)
                          (when msg
                            (s-prefix? "/ZHAW/" (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "afft@zhaw.ch")
                    (mu4e-sent-folder . "/ZHAW/Sent")
                    (mu4e-drafts-folder . "/ZHAW/Drafts")
                    (mu4e-trash-folder . "/ZHAW/Trash")
                    (smtpmail-default-smtp-server . "127.0.0.1")
                    (smtpmail-smtp-server . "127.0.0.1")
                    (smtpmail-local-domain . "127.0.0.1")
                    (smtpmail-smtp-user . "afft@zhaw.ch")
                    (smtpmail-stream-type . plain)
                    (smtpmail-smtp-service . 1026)))
          ,(make-mu4e-context
            :name "Outlook"
            :enter-func (lambda() (mu4e-message "Switch to Outlook"))
            :match-func (lambda(msg)
                          (when msg
                            (s-prefix? "/Outlook/" (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "raffael.affolter@outlook.com")
                    (mu4e-sent-folder . "/Outlook/Sent")
                    (mu4e-drafts-folder . "/Outlook/Drafts")
                    (mu4e-trash-folder . "/Outlook/Trash")
                    (smtpmail-default-smtp-server . "smtp.office365.com")
                    (smtpmail-smtp-server . "smtp.office365.com")
                    (smtpmail-local-domain . "outlook.com")
                    (smtpmail-smtp-user . "raffael.affolter@outlook.com")
                    (smtpmail-stream-type . starttls)
                    (smtpmail-smtp-service . 587)
                    (mu4e-sent-messages-behavior . delete)
                    (mu4e-sent-messages-behavior . delete)))
          ,(make-mu4e-context
            :name "UZH"
            :enter-func (lambda() (mu4e-message "Switch to UZH"))
            :match-func (lambda(msg)
                          (when msg
                            (s-prefix? "/UZH/" (mu4e-message-field msg :maildir))))
            :vars '((user-mail-address . "raffael.golomingi@uzh.ch")
                    (mu4e-sent-folder . "/UZH/Gesendet")
                    (mu4e-drafts-folder . "/UZH/Drafts")
                    (mu4e-trash-folder . "/UZH/Trash")
                    (smtpmail-default-smtp-server . "smtp.uzh.ch")
                    (smtpmail-smtp-server . "smtp.uzh.ch")
                    (smtpmail-local-domain . "uzh.ch")
                    (smtpmail-smtp-user . "raffael.golomingi@uzh.ch")
                    (smtpmail-stream-type . starttls)
                    (smtpmail-smtp-service . 587)))))

  (add-hook 'message-mode-hook 'turn-on-orgtbl)
;;  (add-hook 'message-mode-hook 'turn-on-orgstruct++)
  (add-hook 'mu4e-compose-mode-hook 'flyspell-mode)
  (add-hook 'mu4e-compose-mode-hook (lambda() (ispell-change-dictionary "de_CH"))))

(use-package mu4e-icalendar
  :after (mu4e)
  :config
  (mu4e-icalendar-setup)
  (setq gnus-icalendar-org-capture-file "~/Dokumente/org-documents/agenda.org")
  (setq gnus-icalendar-org-capture-headline '("Termine"))
  (gnus-icalendar-org-setup))
#+end_src


* flyspell
we want flyspell to be enabled by default in text org and latex files

#+begin_src emacs-lisp
(setq ispell-list-command "--list")
(setq ispell-dictionary "de_CH")
(add-hook 'text-mode-hook 'flyspell-mode)
(diminish 'flyspell-mode)
#+end_src

also easy swich between english and german

#+begin_src emacs-lisp
(defun fd-switch-dictionary()
  (interactive)
  (let* ((dic ispell-current-dictionary)
         (change (if (string= dic "de_CH") "english" "de_CH")))
    (ispell-change-dictionary change)
    (message "Dictionary switched from %s to %s" dic change)))

(global-set-key (kbd "<f8>")   'fd-switch-dictionary)
#+end_src

* Languagetool

 #+begin_src emacs-lisp
(use-package languagetool
  :ensure t
  :config
  (setq languagetool-java-arguments '("-Dfile.encoding=UTF-8")
        languagetool-console-command "~/.languagetool/languagetool-commandline.jar"
        languagetool-server-command "~/.languagetool/languagetool-server.jar"
        languagetool-mother-tongue t
        languagetool-default-language "de-CH")
  (global-set-key (kbd "C-c l c") 'languagetool-check)
  (global-set-key (kbd "C-c l d") 'languagetool-clear-buffer)
  (global-set-key (kbd "C-c l p") 'languagetool-correct-at-point)
  (global-set-key (kbd "C-c l b") 'languagetool-correct-buffer)
  (global-set-key (kbd "C-c l l") 'languagetool-set-language))
 #+end_src


* Markdown
#+begin_src emacs-lisp
(use-package markdown-mode
  :ensure t
  :mode (("README\\.md\\'" . gfm-mode)
         ("\\.md\\'" . markdown-mode)
         ("\\.markdown\\'" . markdown-mode))
  :init (setq markdown-command "pandoc"))
#+end_src

#+begin_src emacs-lisp
(use-package markdown-preview-mode
  :ensure t)
#+end_src

* Px

Px lets you preview LaTeX snippets.

#+begin_src emacs-lisp
(use-package px
  :ensure t)
#+end_src
* Latex

#+begin_src emacs-lisp
(use-package auctex
  :defer t
  :ensure t)
#+end_src

* Programming settings
** Defaults

Line numbers

#+begin_src emacs-lisp
(global-display-line-numbers-mode)
#+end_src

Tabs

#+begin_src emacs-lisp
(setq-default tab-width 2)
#+end_src

Use 2 spaces instead of tab.

#+begin_src emacs-lisp
(setq-default tab-width 2 indent-tabs-mode nil)
#+end_src

intendation cannot insert tabs

#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
#+end_src

Two spaces for programming languages

#+begin_src emacs-lisp
(add-hook 'python-mode-hook
          (lambda ()
            (setq python-indent-offset 4)))
(setq js-indent-level 2)
#+end_src

No trailing white spaces except in makrdowns

#+begin_src emacs-lisp
(add-hook 'before-save-hook
          '(lambda()
             (when (not (derived-mode-p 'markdown-mode))
               (delete-trailing-whitespace))))

#+end_src

highlight fixme todo and bug statement

#+begin_src emacs-lisp
;;(use-package fixme-mode
;;  :ensure t
;;  :config (fixme-mode nil))
#+end_src

highlight all characters which are over the column 100 and show a visual line

#+begin_src emacs-lisp
(require 'whitespace)
(setq whitespace-line-column 100)
(setq whitespace-style '(face lines-tail))

(add-hook 'prog-mode-hook 'whitespace-mode)
(add-hook 'prog-mode-hook (lambda () (set-fill-column 100)))
(add-hook 'prog-mode-hook 'display-fill-column-indicator-mode)
(diminish 'whitespace-mode)
#+end_src

Use python3 as default
#+begin_src  emacs-lisp
(setq python-shell-interpreter "python3")
#+end_src

diminish eldoc-mode

#+begin_src emacs-lisp
(diminish 'eldoc-mode)
#+end_src

** realgud
Realgud is a frontend for external debuggers.

#+begin_src  emacs-lisp
(use-package realgud
  :ensure t
  :defer t)
#+end_src

** Paredit

#+begin_src emacs-lisp
;;(use-package paredit
;;  :ensure t
;;  :diminish paredit-mode
;;  :config
;;  (autoload 'enable-paredit-mode "paredit"
;;    "Turn on pseudo-structural editing of Lisp code." t)
;;  (add-hook 'lisp-mode-hook 'enable-paredit-mode)
;;  (add-hook 'emacs-lisp-mode-hook 'enable-paredit-mode)
;;  (add-hook 'lisp-interaction-mode-hook 'enable-paredit-mode)
;;  ;(add-hook 'helm-mode-hook 'enable-paredit-mode)
;;  (add-hook 'json-mode-hook 'enable-paredit-mode)
;;  (add-hook 'scheme-mode-hook 'enable-paredit-mode)
;;  (add-hook 'geiser-repl-mode-hook 'enable-paredit-mode)
;;  (add-hook 'slime-repl-mode-hook 'enable-paredit-mode)
;;  (add-hook 'hy-mode-hook 'enable-paredit-mode
;; ;; (add-hook 'clojure-mode-hook 'enable-paredit-mode)
;;;;  (add-hook 'cider-repl-mode-hook 'enable-paredit-mode)
;;)
;;)

#+end_src

** Smartparens
#+begin_src emacs-lisp
(use-package smartparens
  :ensure t
  :diminish smartparens-mode
  :hook ((lisp-mode
          emacs-lisp-mode
          json-mode
          scheme-mode
          geiser-repl-mode
          slime-repl-mode
          hy-mode
          clojure-mode
          cider-repl-mode
          haskell-mode
          haskell-interactive-mode
          ess-mode
          ein:ipynb-mode
          python-mode) . smartparens-strict-mode)
  :config
  (require 'smartparens-config)
  (sp-use-smartparens-bindings))
#+end_src

** LISP settings

#+begin_src emacs-lisp


#+end_src

** Clojure

#+begin_src emacs-lisp
(use-package clojure-mode
  :ensure t)

(use-package clojure-mode-extra-font-locking
  :ensure t)
#+end_src

** Cider

#+begin_src emacs-lisp
(use-package cider
  :ensure t
  :diminish cider-mode)

(setq cider-cljs-lein-repl
      "(do (require 'figwheel-sidecar.repl-api)
           (figwheel-sidecar.repl-api/start-figwheel!)
           (figwheel-sidecar.repl-api/cljs-repl))")
#+end_src

** SLIME

#+begin_src emacs-lisp
(use-package slime
  :ensure t
  :config (progn (setq inferior-lisp-program "/usr/bin/clisp")
                 (setq slime-contribs '(slime-fancy))))

#+end_src

** Geiser

We want a good racket workspace

#+begin_src emacs-lisp
(use-package geiser
  :ensure t
  :config
  (setq geiser-active-implementations '(racket)))
#+end_src

** Hy
#+begin_src emacs-lisp
(use-package hy-mode
  :ensure t)
#+end_src
** Magit

#+begin_src emacs-lisp
(use-package magit
  :ensure t
  :config (global-set-key (kbd "C-x g") 'magit-status))

#+end_src

** flycheck

#+begin_src emacs-lisp
(use-package flycheck
  :ensure t
  :diminish flycheck-mode
  :init (global-flycheck-mode))
#+end_src


** Rainboooows

#+begin_src emacs-lisp
(use-package rainbow-delimiters
  :ensure t
  :init
  (add-hook 'prog-mode-hook #'rainbow-delimiters-mode))
#+end_src

** Yaml

#+begin_src emacs-lisp
(use-package yaml-mode
  :ensure t)
#+end_src

** ESS
we use ESS for R
#+begin_src emacs-lisp
(use-package ess
  :ensure t
  :init (require 'ess-site)
  ;(load "ess-autoloads")
  )
#+end_src

** Jupyter support

#+begin_src emacs-lisp
(use-package ein
  :ensure t
  :defer t)
#+end_src

** Haskell
#+begin_src emacs-lisp
(use-package haskell-mode
  :ensure t
  :config
  (require 'haskell-interactive-mode)
  (require 'haskell-process)
  (add-hook 'haskell-mode-hook 'interactive-haskell-mode)
  (custom-set-variables '(haskell-process-type 'ghci))
  (define-key haskell-mode-map (kbd "C-c C-c") 'haskell-compile)
  (define-key haskell-mode-map (kbd "C-c C-l") 'haskell-process-load-or-reload)
  (define-key haskell-mode-map (kbd "C-`") 'haskell-interactive-bring)
  (define-key haskell-mode-map (kbd "C-c C-t") 'haskell-process-do-type)
  (define-key haskell-mode-map (kbd "C-c C-i") 'haskell-process-do-info)
  (define-key haskell-mode-map (kbd "C-c C-c") 'haskell-process-cabal-build)
  (define-key haskell-mode-map (kbd "C-c C-k") 'haskell-interactive-mode-clear)
  (define-key haskell-mode-map (kbd "C-c c") 'haskell-process-cabal))
#+end_src


** Gnuplot
#+begin_src emacs-lisp
(use-package gnuplot
  :ensure t)
#+end_src

* Org-Mode Settings
** org easy templates
This section maybe gets removed but I lost the org easy templates

#+begin_src emacs-lisp
(require 'org-tempo)
#+end_src

** configure latex compiler
#+begin_src emacs-lisp
;;  (setq org-latex-compiler "xelatex")
#+end_src

** configure pdflatex
#+begin_src emacs-lisp
(setq org-latex-pdf-process
      '("pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "bib2gls --group %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "bibtex %b"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"
        "pdflatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src

** Org-src settings
Enable native intendations in sourc blocks and lets open the org-src-edit b

#+begin_src emacs-lisp
(setq org-src-tab-acts-natively t)
(setq org-src-preserve-indentation t)
(setq org-fontify-whole-heading-line t)
(setq org-src-window-setup 'split-window-right)
#+end_src

** KOMA-SCRIPT
we want koma script

#+begin_src emacs-lisp

  (with-eval-after-load "ox-latex"
    (add-to-list 'org-latex-classes
                 '("koma-article" "\\documentclass{scrartcl}"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                   ("\\paragraph{%s}" . "\\paragraph*{%s}")
                   ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))

  (with-eval-after-load "ox-latex"

    (add-to-list 'org-latex-classes
                 '("koma-letter"
                   "\\documentclass[11pt]{scrlttr2}"
                   "\\usepackage[utf8]{inputenc}"
                   "\\usepackage[T1]{fontenc}"
                   "\\usepackage{xcolor}"
                   ("\\section{%s}" . "\\section*{%s}")
                   ("\\subsection{%s}" . "\\subsection*{%s}")
                   ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                   ("\\paragraph{%s}" . "\\paragraph*{%s}")
                   ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))

#+end_src

** eurpecv-class

#+begin_src emacs-lisp
(with-eval-after-load "ox-latex"
  (add-to-list 'org-latex-classes
               '("europecv" "\\documentclass[utf8,a4Paper, 10pt, helvetica,narrow,flagWB, booktabs,totpages,german]{europevc}")))
#+end_src

** ACMART

#+begin_src emacs-lisp
(with-eval-after-load "ox-latex"
  (add-to-list 'org-latex-classes
               '("acmart" "\\documentclass{acmart}"
                 ("\\section{%s}" . "\\section*{%s}")
                 ("\\subsection{%s}" . "\\subsection*{%s}")
                 ("\\subsubsection{%s}" . "\\subsubsection*{%s}")
                 ("\\paragraph{%s}" . "\\paragraph*{%s}")
                 ("\\subparagraph{%s}" . "\\subparagraph*{%s}"))))
#+end_src

** org latex settings

I want to use minted to highlight my code.

#+begin_src emacs-lisp
(add-to-list 'org-latex-packages-alist '("" "minted"))
(setq org-latex-listings 'minted)
(setq org-latex-prefer-user-labels t)
#+end_src

** Plain lists

#+begin_src emacs-lisp
(setq org-list-allow-alphabetical t)
#+end_src

** Hyperlink display
For easier writing i will use literal links
#+begin_src emacs-lisp
(setq org-descriptive-links nil)
#+end_src

** where is my agenda

#+begin_src emacs-lisp
(setq org-agenda-files '("~/Dokumente/org-documents/agenda.org"
                         "~/Dokumente/ZHAW-Scansor-Projekt/scansor-project.org"
                         "~/Dokumente/org-documents/irm-agenda.org"
                         "~/Dokumente/org-documents/zhaw-agenda.org"))
#+end_src

** Bibtex settings

#+begin_src emacs-lisp
(setq my-bibtex-dir "~/bibliography/"
      my-bibtex-pdf-dir (concat my-bibtex-dir "bibtex-pdfs/")
      my-default-bibfile (list  (concat my-bibtex-dir "default-bibliography.bib"))
      my-default-bibnotes my-bibtex-dir)
#+end_src

Definitions for automatically generating a bibtex key from a bibtex
entry. Look at help:bibtex-generate-autokey to understand the settings
#+begin_src emacs-lisp
(setq bibtex-autokey-year-length 4
      bibtex-autokey-name-year-separator "-"
      bibtex-autokey-year-title-separator "-"
      bibtex-autokey-titleword-separator "-"
      bibtex-autokey-titlewords 2
      bibtex-autokey-titlewords-stretch 1
      bibtex-autokey-titleword-length 5)
#+end_src

** org capture templates
#+begin_src emacs-lisp
(defun name-blog-file ()
  (interactive)
  (let ((name (read-string "Name: ")))
    (expand-file-name (format "%s/%s-%s.org"
                              (format-time-string "%Y")
                             (format-time-string "%Y-%m-%d")
                              name) "~/git/cerealbuster.gitlab.io/org/posts/")))

(setq org-capture-templates
      '(("t" "Task" entry (file+headline "" "Tasks")
         "* TODO %?\n  %u\n  %a")
        ("b" "New blog entry" plain (file name-blog-file)
         (file "~/git/cerealbuster.gitlab.io/templates/blog-capture.org"))))

;;("#" "used by gnus-icalendar-org" entry
;; (file+olp+datetree  "~/Dokumente/org-documents/agenda.org")
;; "%i" :immediate-finish t)


;(defun my-catch-event-time (orig-fun &rest args)
;  "Set org-overriding-default-time to the start time of the capture event"
;  (let ((org-overriding-default-time (date-to-time
;                                      (gnus-icalendar-event:start (car args)))))
;    (apply orig-fun args)))

;(advice-add 'gnus-icalendar:org-event-save :around #'my-catch-event-time)
#+end_src


** Citeproc
   #+begin_src emacs-lisp
(use-package citeproc
  :ensure t)
   #+end_src

** Org-Ref

#+begin_src emacs-lisp
(use-package org-ref
  :ensure t
  ;;:commands org-ref-bibtex-hydra/body
  :config
  (setq org-ref-notes-directory my-bibtex-dir
        org-ref-default-bibliography my-default-bibfile
        org-ref-bibliography-notes my-default-bibnotes
        org-ref-pdf-directory my-bibtex-pdf-dir)
  (setq org-ref-notes-function
        (lambda (thekey)
          (let ((bibtex-completion-bibliography
                 (org-ref-find-bibliography)))
            (bibtex-completion-edit-notes
             (list
              (car (org-ref-get-bibtex-key-and-file thekey))))))))
#+end_src

** Org-noter
#+begin_src emacs-lisp
(use-package org-noter
  :ensure t
  :config
  (setq org-noter-notes-search-path (list my-default-bibnotes))
  :bind ("C-c i" . 'org-noter-insert-note))
#+end_src

** helm bibtex
#+begin_src emacs-lisp
(use-package helm-bibtex
  :ensure t
  :commands helm-bibtex
  :config
  (setq helm-bibtex-bibliography my-default-bibfile ;; where your references are stored
        helm-bibtex-library-path my-bibtex-pdf-dir ;; where your pdfs etc are stored
        bibtex-completion-bibliography my-default-bibfile
        bibtex-completion-notes-path my-default-bibnotes
        ;; name of note-file will be {pdffile} + extension
        bibtex-completion-notes-extension ".org"
        bibtex-completion-notes-template-multiple-files
        (format
         "#+TITLE: Notes on ${=key=}: ${title}\n#+INTERLEAVE_PDF: %s${=key=}.pdf\n\n"
         my-bibtex-pdf-dir)       ;; header to be used in the associated notes files
        bibtex-completion-additional-search-fields '(keywords)))
#+end_src

** Org bullets makes things look pretty

#+begin_src emacs-lisp
  (setenv "BROWSER" "chromium-browser")
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1))))
#+end_src
** Subfigures
   #+begin_src emacs-lisp
(use-package ox-latex-subfigure
  :ensure t)
   #+end_src

** Org mu4e

#+begin_src emacs-lisp
(use-package org-mu4e)
#+end_src

** OrgMsg
   #+begin_src emacs-lisp
(use-package org-msg
  :ensure t
  :config
  (setq mail-user-agent 'mu4e-user-agent)
  (setq
   org-msg-options "html-postamble:nil H:5 num:nil ^:{} toc:nil author:nil email:nil \\n:t"
	 org-msg-startup "hidestars indent inlineimages"
	 org-msg-greeting-fmt "\nHallo%s\n\n"
	 org-msg-greeting-name-limit 3
	 org-msg-default-alternatives '((new		. (text html))
				                          (reply-to-html	. (text html))
				                          (reply-to-text	. (text)))
	 org-msg-convert-citation t
	 org-msg-signature "
Beste Grüsse
Raffael

,#+begin_signature
--

,#+include: \"~/.signature\"

,#+end_signature")
(org-msg-mode)
(dolist (cur org-msg-enforce-css)
  (when (and (assoc 'font-family (caddr cur))
	     (not (string= (assoc-default 'font-family (caddr cur)) "monospace")))
    (setf (alist-get 'font-family (caddr cur)) "\"IBM Plex Sans\"")
    (when (assoc 'font-size (caddr cur))
      (setf (alist-get 'font-size (caddr cur)) "12pt"))
    (when (assoc 'line-height (caddr cur))
      (setf (alist-get 'line-height (caddr cur)) "1.5em")))))
   #+end_src

** enable Markdown export

#+begin_src emacs-lisp
(with-eval-after-load 'org
  (require 'ox-md nil t))
#+end_src

** Org-Journal

#+begin_src emacs-lisp
(use-package org-journal
  :defer t
  :ensure t
  :init
  (setq org-journal-dir "~/Dokumente/org-documents/journals")
  (setq org-journal-file-format "%d-%m-%Y.org"))
#+end_src

** Org-Projects
here are my project settings
#+begin_src emacs-lisp
;(add-to-list 'org-export-options-alist '(:page-type "PAGE_TYPE" "default" nil parse))
#+end_src

#+begin_src emacs-lisp
(defun my/sitemap-fn (title list)
  "Generate the sitemap (Blog Main Page)"
  (concat "#+TITLE: " title "\n\n"
          (string-join (mapcar #'car (cdr list)) "\n\n")))

(defun my/sitemap-entry (entry style project)
  "I create a custom sitemap entry"
  (format (string-join
           '("[[file:%s][%s]]"
             "#+BEGIN_published"
             "%s"
             "#+END_published"
             )"\n")
          entry
          (org-publish-find-title entry project)
          (format-time-string "%d-%m-%Y" (org-publish-find-date entry project))))

(setq org-publish-project-alist

        '(("static-sites"
           :base-directory "~/git/cerealbuster.gitlab.io/org/"
           :base-extension "org"
           :publishing-directory "~/git/cerealbuster.gitlab.io/"
           :publishing-function org-html-publish-to-html
           :recursive t
           :exclude "posts/"
           :headline-levels 4
           :section-numbers nil
           :auto-preamble t
           :html-link-home "index.html"
           :html-link-up "index.html"
           :html-doctype "html5"
           :with-toc nil
           )
          ("blog-posts"
           :base-directory "~/git/cerealbuster.gitlab.io/org/"
           :base-extension "org"
           :publishing-directory "~/git/cerealbuster.gitlab.io/"
           :publishing-function org-html-publish-to-html
           :recursive t
           :headline-levels 4
           :section-numbers nil
           :auto-preamble t
           :auto-sitemap t
           :exclude "index.org\\|about.org"
           :sitemap-filename "sitemap.org"
           :sitemap-title "sitemap"
           :sitemap-style list
           :sitemap-sort-files anti-chronologically
           :sitemap-format-entry my/sitemap-entry
           :html-link-home "../../index.html"
           :html-link-up "../../index.html"
           :html-doctype "html5"
           :with-toc nil)
          ("org-static"
           :base-directory "~/git/cerealbuster.gitlab.io/"
           :publishing-directory "~/git/cerealbuster.gitlab.io/"
           :base-extension "css\\|js\\|png\\|jpg\\|gif\\|pdf\\|mp3\\|ogg\\|swf"
           :recursive t
           :publishing-function org-publish-attachment)
          ("org" :components ("blog-posts" "static-sites" "org-static"))))
#+end_src

** ob-hy
#+begin_src emacs-lisp
(use-package ob-hy
  :ensure t)
#+end_src

** org-babel
This languages shoud be loaded when creating code
#+begin_src emacs-lisp
(org-babel-do-load-languages
 'org-babel-load-languages
 '((python . t)
   (lisp . t)
   (clojure . t)
   (hy . t)
   (scheme . t)
   (R . t)
   (ein .t )
   (shell . t)
   (gnuplot . t)
   (plantuml . t)))
(setq org-babel-clojure-backend 'cider)
(setq org-babel-python-command "python3")
#+end_src

** org-babel-eval-in-repl

Sometimes its nice to just evaluate the codeblock in the repl

#+begin_src emacs-lisp
(use-package org-babel-eval-in-repl
  :ensure t
  :after ob
  :config
  (define-key org-mode-map (kbd "C-<return>") 'ober-eval-in-repl)
  (define-key org-mode-map (kbd "M-S-<return>") 'ober-eval-block-in-repl))
#+end_src

** hooks for orgmode
Update dynamic blocks before saving

#+begin_src emacs-lisp
(add-hook 'before-save-hook 'org-update-all-dblocks)
#+end_src

** org export settings
I prefer that org uses emacs to visit pdfs
#+begin_src emacs-lisp
(setq org-file-apps '((auto-mode . emacs)
                      ("\\.mm\\'" . default)
                      ("\\.x?html?\\'" . default)
                      ("\\.pdf\\'" . emacs)))
#+end_src

* Golden Ratio

#+begin_src emacs-lisp
(use-package golden-ratio
  :ensure t
  :diminish golden-ratio-mode
  :init (setq golden-ratio-auto-scale t)
  :config
  (golden-ratio-mode 1)
  (dolist (f '(ace-window
               ace-delete-window
               ace-select-window
               ace-swap-window
               ace-maximize-window
               avy-pop-mark
               buf-move-left
               buf-move-right
               buf-move-up
               buf-move-down
               evil-avy-goto-word-or-subword-1
               evil-avy-goto-line
               evil-window-delete
               evil-window-split
               evil-window-vsplit
               evil-window-left
               evil-window-right
               evil-window-up
               evil-window-down
               evil-window-bottom-right
               evil-window-top-left
               evil-window-mru
               evil-window-next
               evil-window-prev
               evil-window-new
               evil-window-vnew
               evil-window-rotate-upwards
               evil-window-rotate-downwards
               evil-window-move-very-top
               evil-window-move-far-left
               evil-window-move-far-right
               evil-window-move-very-bottom
               next-multiframe-window
               previous-multiframe-window
               quit-window
               winum-select-window-0-or-10
               winum-select-window-1
               winum-select-window-2
               winum-select-window-3
               winum-select-window-4
               winum-select-window-5
               winum-select-window-6
               winum-select-window-7
               winum-select-window-8
               winum-select-window-9
               windmove-left
               windmove-right
               windmove-up
               windmove-down))
    (add-to-list 'golden-ratio-extra-commands f)))
#+end_src
* Ledger Mode
  Lets try ledger mode
#+begin_src emacs-lisp
(use-package ledger-mode
  :ensure t)
#+end_src

* Writegood Mode

#+begin_src emacs-lisp
(use-package writegood-mode
  :ensure t
  :config
  (global-set-key (kbd "C-c g") 'writegood-mode)
  (global-set-key (kbd "C-c C-g g") 'writegood-grade-level)
  (global-set-key (kbd "C-c C-g e") 'writegood-reading-ease))
#+end_src
* Centered window mode

This centers the text on the window.
#+begin_src emacs-lisp
(use-package centered-window
  :ensure t)
#+end_src

* Skeletons
** Publication skeleton

#+begin_src emacs-lisp

(define-skeleton new-publication
  "Inserts a pubication skeletion into the current buffer
The buffer should be emtpy"
  nil
  "#+options: ':nil *:t -:t ::t <:t H:3 \\n:nil ^:t arch:headline\n"
  "#+options: author:nil broken-links:nil c:nil creator:nil\n"
  "#+options: d:(not LOGBOOK) date:t e:t email:nil f:t inline:t num:t\n"
  "#+options: p:nil pri:nil prop:nil stat:t tags:t tasks:t tex:t\n"
  "#+options: timestamp:t title:nil toc:nil todo:t |:t\n"
  "#+title: " (file-name-base buffer-file-name) "\n"
  "#+latex_class: acmart\n"
  "#+latex_class_options: [11pt,nonacm,screen,acmsmall,urlbreakonhyphens,review=true,anonymous=false]\n"
  "#+latex_header: \\usepackage{natbib}\n"
  "#+latex_header: \\author{Raffael Affolter}\n"
  "#+latex_header: \\email{raffael.affolter@virtopsy.com}\n"
  "#+latex_header:\\affiliation{ \\institution{University of Zurich}\\department{Institute of Forensic Medicine}\\streetaddress{Winterthurerstrasse 190/52}\\city{Zurich} \\country{Switzerland} \\postcode{CH-8057}}\n"
  "#+latex_header_extra:\n"
  "#+description:\n"
  "#+keywords:\n"
  "#+subtitle:\n"
  "#+latex_compiler: pdflatex\n"
  "#+date: \\today\n"
  "\\setcopyright{none}\n"
  "#+begin_abstract\n"
  "1. General statement introducing broad research area of the particular topic\n"
  "2. Explanation of the specific problem (difficulties, obstacles challenge) to be solved\n"
  "3. Review of existing or standard solutions to this problem and their limitations\n"
  "4. An outline of the proposed new solution\n"
  "5. A summary of how the solution was evaluated and what the outcomes of the evaluation where\n"
  "#+end_abstract\n"
  "\\maketitle\n"
  "* Introduction\n"
  "1. why is the problem interesting?\n"
  "2. what are the relevant issues?\n"
  "3. why is the taken apporoach good?\n"
  "4. why are the outcomes significant?\n"
  "* Methodology\n\n"
  "* Results\n\n"
  "* Discussion\n\n"
  "* Conclusions\n\n"
  "Draw together the topics discussed and look beyond\n"
  "#+begin_acks\n\n"
  "Acknowledgements\n"
  "#+end_acks\n\n"
  "bibliographystyle:ACM-Reference-Format\n"
  "bibliography:"(car my-default-bibfile)"\n"

  )
#+end_src

** Blog skeleton
#+begin_src emacs-lisp
(define-skeleton new-blog-entry-skel
  "Inserts a new blog skeleton into the current buffer"
  nil
  (org-export-insert-default-template 'default)
  "#+options: html-link-use-abs-url:nil html-postamble:auto\n"
  "#+options: html-preamble:t html-scripts:t html-style:t\n"
  "#+options: html5-fancy:nil tex:t\n"
  "#+html_doctype: html5\n"
  "#+html_container: article\n"
  "#+description:\n"
  "#+keywords:\n"
  "#+html_link_home: ../../index.html\n"
  "#+html_link_up: ../../index.html\n"
  "#+html_mathjax:\n"
  "#+html_equation_reference_format: \eqref{%s}"
  "#+html_head:\n"
  "#+html_head_extra: <link rel=stylesheet type=text/css href=../../css/main.css />\n"
  "#+infojs_opt:\n"
  "#+creator: <a href=https://www.gnu.org/software/emacs/ >Emacs</a> 26.3 (<a href= https://orgmode.org>Org</a> mode 9.1.9)\n"
  "\n"
  "#+include: ../../../includes/disqus.html export html\n")

(defun new-blog-entry ()
  (interactive)
  (find-file (name-blog-file))
  (new-blog-entry-skel))
#+end_src


* EXWM

#+begin_src emacs-lisp :exports none
(use-package exwm
  :ensure t
  :defer t
  :config
  (require 'exwm-config)
  (require 'exwm-systemtray)
  (exwm-config-misc)
  (setq exwm-workspace-number 4)
  (exwm-systemtray-enable)
  (setq exwm-systemtray-height 15)
  (setq exwm-input-global-keys
        `(
          ;; Bind "s-r" to exit char-mode and fullscreen mode.
          ([?\s-r] . exwm-reset)
          ;; Bind "s-w" to switch workspace interactively.
          ([?\s-w] . exwm-workspace-switch)
          ;; Bind "s-0" to "s-9" to switch to a workspace by its index.
          ,@(mapcar (lambda (i)
                      `(,(kbd (format "s-%d" i)) .
                        (lambda ()
                          (interactive)
                          (exwm-workspace-switch-create ,i))))
                    (number-sequence 0 9))
          ;; Bind "s-&" to launch applications ('M-&' also works if the output
          ;; buffer does not bother you).
          ([?\s-&] . (lambda (command)
                       (interactive (list (read-shell-command "$ ")))
                       (start-process-shell-command command nil command)))
          ;; Bind "s-<f2>" to "slock", a simple X display locker.
          ([s-f2] . (lambda ()
                      (interactive)
                      (start-process "" nil "/usr/bin/slock")))
          ([?\s-p] . helm-run-external-command)
          ([?\s-:] . evil-ex))))
#+end_src

* desktop-environment

#+begin_src emacs-lisp :exports none
(use-package desktop-environment
  :ensure t
  :diminish desktop-environment-mode
  :config (desktop-environment-mode))
#+end_src
